### ISSUE TITLE
Wrong tranlation of organization attributes from Groovy to XML

### ISSUE THREAD

**Issue by giflw** [takari/polyglot-maven#110]
Hi
I was testing the groovy DSL translation to XML, Given a `pom.groovy` with organization name and url setted, the XML translation generates name and url as xml attributes of organization instead of tags.

pom.groovy
```groovy
project(modelVersion: '4.0.0', groupId: 'group-id', artifactId: 'artifact-id') {

  version '0.0.0-SNAPSHOT'

  organization(name: 'Organization Name', url: 'http://organization.url')

}
```

Generated pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?><project xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd" xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>group-id</groupId>
  <artifactId>artifact-id</artifactId>
  <version>0.0.0-SNAPSHOT</version>
  <organization name="Organization Name" url="http://organization.url" />
</project>
```

**Comment by jdillon** [comment]
I don’t recall if there was handling for organization attributes.  Maven XML generally does not use attributes and the Groovy POM format is really meant to be as close to the XML as possible, so adding attributes instead of child elements is not really valid.

organization(name: 'Organization Name', url: 'http://organization.url')

but this should be:

organization {
	name 'Organization Name’
        url 'http://organization.url'
}

—jason

On November 30, 2016 at 4:56:51 PM, Guilherme I F L Weizenmann (notifications@github.com) wrote:

Hi
I was testing the groovy DSL translation to XML, Given a pom.groovy with organization name and url setted, the XML translation generates name and url as xml attributes of organization instead of tags.

pom.groovy

project(modelVersion: '4.0.0', groupId: 'group-id', artifactId: 'artifact-id') {

  version '0.0.0-SNAPSHOT'

  organization(name: 'Organization Name', url: 'http://organization.url')

}
Generated pom.xml:

<?xml version="1.0" encoding="UTF-8"?><project xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd" xmlns="http://maven.apache.org/POM/4.1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>group-id</groupId>
  <artifactId>artifact-id</artifactId>
  <version>0.0.0-SNAPSHOT</version>
  <organization name="Organization Name" url="http://organization.url" />
</project>

**Comment by giflw** [comment]
Thanks! I didn't notice that. Now it's working! :smiley:
