### ISSUE TITLE
JDK9 support for polyglot-ruby

### ISSUE THREAD

**Issue by headius** [takari/polyglot-maven#123]
We need a release of polyglot-ruby that runs on JDK 9.

I believe the main update necessary is just to use a more recent JRuby, like JRuby 9.1.8.0, which has fixes to run correctly under JDK9's module system.

Other dependencies may need to be upgrade as well.

In the short term, if there's a way to force the polyglot-ruby extension to use JRuby 9.1.8.0, I would appreciate help figuring that out :-)

**Comment by mosabua** [comment]
What about just updating jruby here https://github.com/takari/polyglot-maven/blob/master/polyglot-ruby/pom.xml#L32

I am hoping to work towards a polyglot release in the next weeks so this would be a great addition.. I might be able to look at things after some other takari releases I am on at the moment...

**Comment by mkristian** [comment]
@mosabua did just update the jruby version. are there any blockers for the polyglot release right now ?

**Comment by mosabua** [comment]
I dont know .. I have to check things out. I am in the process of getting a new takari-pom parent released, and wrapper and maven plugin... all for Maven 3.5.0 .. I would like to use that parent here and then see what else there is to fix.

**Comment by mosabua** [comment]
Also ... @mkristian does that little change fix the usage with Java 9 .. I have not done any testing on that..

**Comment by mkristian** [comment]
@mosabua jruby tries to be runnable with java-9 so the latest jruby version is the best for java9. currently the jruby teams look into building jruby with jdk9 and for this the ruby POMs need to work. 

in short yes this patch is good and works for me and I deployed a snapshot.

but the problem is that picking a snapshot polyglot-ruby needs a custom settings.xml or local build to pick it up, that is why a new release is welcome. my tests yesterday showed that a jruby build with java-9  is not really close ... but the first step is getting the dev-environment in working condition ;)

**Comment by mosabua** [comment]
Sounds good. I will do a polyglot maven release this week or latest next week.

**Comment by mkristian** [comment]
@mosabua thanks

**Comment by mosabua** [comment]
Release is out. https://github.com/takari/polyglot-maven/issues/125
