### ISSUE TITLE
Release 0.5.0 vulnerabilities report

### ISSUE THREAD

**Issue by cstamas** [takari/polyglot-maven#276]
Seems scala is flagged as vulnerable
https://ossindex.sonatype.org/component/pkg:maven/org.scala-lang/scala-compiler@2.11.12?utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0

**Comment by cstamas** [comment]
@lefou

**Comment by cstamas** [comment]
The complete report https://sbom.sonatype.com/report/T1-118f0f57da8c6b3097cc-546c0fefd37fe5-1698961020-0f326982c4c0479a9ea423b29d5d01f5

**Comment by lefou** [comment]
Looks like we finally can update to Scala 2.12, which is AFAIK the last version supported by `com.twitter:util-eval`. This is possible, since we lifted the minimal supported Java version to 8.

https://github.com/takari/polyglot-maven/blob/801746a265c0919fc8187dc5a87acc6fc23075c0/polyglot-scala/pom.xml#L23-L25
