### ISSUE TITLE
.tesla.xxx.pom issues

### ISSUE THREAD

**Issue by huntc** [takari/polyglot-maven#3]
As of commit bfc16c7, the creation of a `.tesla.xxx.pom` poses some new issues:
- developers will be expected to have their scm ignore `.tesla*` files;
- the encoding of a model to xml consumes more time vs using an xml directly; and most importantly
- the encoded `.tesla.xxx.pom` must conform to any restrictions imposed on the pom it was produced from.

I'm particularly concerned about the restriction conformance. For example on the tesla modules, the poms must have license headers. Generated poms do have such headers of course.

The approach of generating a  `.tesla.xxx.pom` is concerning. According to commit bfc16c7 it is because the install plugin requires a pom.xml to deploy. Perhaps there's another way to approach this e.g. have a `translate` occur as part of the install plugin and reference the updated install plugin as part of the tesla build. The `pom.xxx` file should also be installed alongside any `pom.xml`. This approach would also require `pom.xxx` files to have a higher priority than `pom.xml` (which I think is a good thing anyhow).

**Comment by jvanzyl** [comment]
I will take a look shortly to find a general solution.

**Comment by mkristian** [comment]
this is still needed to the extend that the generated ```.polyglot.pom.*``` is at least needed to have ```mvn install``` install the **xml** version of the POM. otherwise you end up with ruby or yaml or scala POMs in your local repo. for ```mvn deploy``` this is probably needed as well for the same reason. other maven plugins might need this as well. for other plugins an early execution of polyglot-translate-plugin would help as workaround.

the 'polyglot.dump.pom' property to permanently dump the temporary pom and pom.xml can be safely removed as the polyglot-translate-plugin can be used instead. maybe an extra config which allows to add this to generated pom.xml: https://github.com/takari/polyglot-maven/blob/master/polyglot-common/src/main/java/org/sonatype/maven/polyglot/TeslaModelProcessor.java#L45

**Comment by lefou** [comment]
What is the current state? I'm working with polyglot-scala in many projects, and there are no issue at all when installing or deploying. An update to this issue would be very appreciated. If the interop issues are solved for all dialects, please note this here, so that I can send a PR for the main README, to reflect the more stable nature of polyglot.

**Comment by mosabua** [comment]
Good question...
