### ISSUE TITLE
[polyglot-groovy] translation of activation > activeByDefault > false generates invalid groovy

### ISSUE THREAD

**Issue by fbricon** [takari/polyglot-maven#57]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo.bar</groupId>
  <artifactId>java</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <profiles>
    <profile>
      <id>badly-translated</id>
      <activation>
        <activeByDefault>false</activeByDefault>
      </activation>
    </profile>
  </profiles>
</project>
``` 
converted to pom.groovy yields

```groovy
project {
  modelVersion '4.0.0'
  groupId 'foo.bar'
  artifactId 'java'
  version '0.0.1-SNAPSHOT'
  profiles {
    profile {
      id 'badly-translated'
      activation
    }
  }
}
```

which is bad groovy: `No such property: activation for class:  org.sonatype.maven.polyglot.groovy.builder.ModelBuilder$1` 

because activeByDefault=false is the default value, it's not rendered, leading to an empty but illegal activation node.

This comes from a real world example https://github.com/jboss-developer/jboss-eap-quickstarts/blob/7.0.x-develop/kitchensink-html5-mobile/pom.xml#L282 (or org.wildfly.archetype:wildfly-html5-mobile-archetype:8.2.0.Final)

**Comment by jdillon** [comment]
This is due to the xml being read by the default (xml) model reader, then written back out using the default (xml) model writer which is producing:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo.bar</groupId>
  <artifactId>java</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <profiles>
    <profile>
      <id>badly-translated</id>
      <activation />
    </profile>
  </profiles>
</project>
```

And the translation to groovy is based on the above using the simple Dom2Groovy mechanism that is not aware of any specific details about models defaults (or really anything at all related to the model).

**Comment by jdillon** [comment]
This is the code block which is problematic:

https://github.com/takari/polyglot-maven/blob/master/polyglot-groovy/src/main/java/org/sonatype/maven/polyglot/groovy/Dom2Groovy.java#L125

I'm not sure however atm if the right solution is to omit elements which have no children or append " {}" so that its a closure block to keep the builder syntax happy, ie:

```
printEnd(" {}", endWithComma);
```

^^^ that does seem to fix it, but I've not tested if this breaks other things yet or not.

**Comment by jdillon** [comment]
Pushed PR https://github.com/takari/polyglot-maven/pull/58

**Comment by jdillon** [comment]
Merged change
